/*
 *  Copyright (C) 2010 nickapos
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * AboutWindow.java
 * This class will create a window with a text area and depending on the need
 * will present in the text are a message, be it an about or a readme.
 * Created on 11 Αυγ 2010, 9:51:33 μμ
 */
package gr.oncrete.nick.myCrop.UserInterface;

import gr.oncrete.nick.myCrop.BusinessLogic.ETo.*;

/**
 *
 * @author nickapos
 */
public class EtWindow extends javax.swing.JFrame {

    /** Creates new form AboutWindow */
    public EtWindow() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField8 = new javax.swing.JTextField();
        etoTabbedPane = new javax.swing.JTabbedPane();
        EaPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        eaTmaxTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        eaTminTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        eaRHMaxTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        eaRHMinTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        eaResultsLabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        eaButton = new javax.swing.JButton();
        EaPoorPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        eaPoorTmaxTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        eaPoortTminTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        eaPoorRhTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        eaPoorResultLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        eaPoorButton = new javax.swing.JButton();
        EtoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        etoTmaxTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        etoTminTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        etoEaTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        etoAirSpeedTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        etoMonthNumberTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        etoLatDegreesTextField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        etoLatitudeMinutesTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        etoAvMonTempTextField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        etoPrevMonthTempTextField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        etoAltitudeTextField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        etoSunHoursTextField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        etoResultsLabel = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        calcEToButton = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        etoKcTextField = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        etResultsLabel = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        calcETButton = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("gr/oncrete/nick/myCrop/UserInterface/Bundle"); // NOI18N
        jTextField8.setText(bundle.getString("EtWindow.jTextField8.text")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(bundle.getString("EtWindow.title")); // NOI18N
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        EaPanel.setLayout(new java.awt.GridLayout(6, 2));

        jLabel8.setText(bundle.getString("EtWindow.jLabel8.text")); // NOI18N
        EaPanel.add(jLabel8);

        eaTmaxTextField.setText(bundle.getString("EtWindow.eaTmaxTextField.text")); // NOI18N
        EaPanel.add(eaTmaxTextField);

        jLabel9.setText(bundle.getString("EtWindow.jLabel9.text")); // NOI18N
        EaPanel.add(jLabel9);

        eaTminTextField.setText(bundle.getString("EtWindow.eaTminTextField.text")); // NOI18N
        EaPanel.add(eaTminTextField);

        jLabel10.setText(bundle.getString("EtWindow.jLabel10.text")); // NOI18N
        EaPanel.add(jLabel10);

        eaRHMaxTextField.setText(bundle.getString("EtWindow.eaRHMaxTextField.text")); // NOI18N
        EaPanel.add(eaRHMaxTextField);

        jLabel11.setText(bundle.getString("EtWindow.jLabel11.text")); // NOI18N
        EaPanel.add(jLabel11);

        eaRHMinTextField.setText(bundle.getString("EtWindow.eaRHMinTextField.text")); // NOI18N
        EaPanel.add(eaRHMinTextField);

        jLabel12.setText(bundle.getString("EtWindow.jLabel12.text")); // NOI18N
        EaPanel.add(jLabel12);

        eaResultsLabel.setText(bundle.getString("EtWindow.eaResultsLabel.text")); // NOI18N
        EaPanel.add(eaResultsLabel);

        jLabel14.setText(bundle.getString("EtWindow.jLabel14.text")); // NOI18N
        EaPanel.add(jLabel14);

        eaButton.setText(bundle.getString("EtWindow.eaButton.text")); // NOI18N
        eaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eaButtonActionPerformed(evt);
            }
        });
        EaPanel.add(eaButton);

        etoTabbedPane.addTab(bundle.getString("EtWindow.EaPanel.TabConstraints.tabTitle"), EaPanel); // NOI18N

        EaPoorPanel.setLayout(new java.awt.GridLayout(5, 2));

        jLabel2.setText(bundle.getString("EtWindow.jLabel2.text")); // NOI18N
        EaPoorPanel.add(jLabel2);

        eaPoorTmaxTextField.setText(bundle.getString("EtWindow.eaPoorTmaxTextField.text")); // NOI18N
        EaPoorPanel.add(eaPoorTmaxTextField);

        jLabel3.setText(bundle.getString("EtWindow.jLabel3.text")); // NOI18N
        EaPoorPanel.add(jLabel3);

        eaPoortTminTextField.setText(bundle.getString("EtWindow.eaPoortTminTextField.text")); // NOI18N
        eaPoortTminTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eaPoortTminTextFieldActionPerformed(evt);
            }
        });
        EaPoorPanel.add(eaPoortTminTextField);

        jLabel4.setText(bundle.getString("EtWindow.jLabel4.text")); // NOI18N
        EaPoorPanel.add(jLabel4);

        eaPoorRhTextField.setText(bundle.getString("EtWindow.eaPoorRhTextField.text")); // NOI18N
        EaPoorPanel.add(eaPoorRhTextField);

        jLabel5.setText(bundle.getString("EtWindow.jLabel5.text")); // NOI18N
        EaPoorPanel.add(jLabel5);

        eaPoorResultLabel.setText(bundle.getString("EtWindow.eaPoorResultLabel.text")); // NOI18N
        EaPoorPanel.add(eaPoorResultLabel);

        jLabel7.setText(bundle.getString("EtWindow.jLabel7.text")); // NOI18N
        EaPoorPanel.add(jLabel7);

        eaPoorButton.setText(bundle.getString("EtWindow.eaPoorButton.text")); // NOI18N
        eaPoorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eaPoorButtonActionPerformed(evt);
            }
        });
        EaPoorPanel.add(eaPoorButton);

        etoTabbedPane.addTab(bundle.getString("EtWindow.EaPoorPanel.TabConstraints.tabTitle"), EaPoorPanel); // NOI18N

        EtoPanel.setLayout(new java.awt.GridLayout(16, 0, 2, 0));

        jLabel1.setText(bundle.getString("EtWindow.jLabel1.text")); // NOI18N
        EtoPanel.add(jLabel1);

        etoTmaxTextField.setText(bundle.getString("EtWindow.etoTmaxTextField.text")); // NOI18N
        EtoPanel.add(etoTmaxTextField);

        jLabel6.setText(bundle.getString("EtWindow.jLabel6.text")); // NOI18N
        EtoPanel.add(jLabel6);

        etoTminTextField.setText(bundle.getString("EtWindow.etoTminTextField.text")); // NOI18N
        etoTminTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etoTminTextFieldActionPerformed(evt);
            }
        });
        EtoPanel.add(etoTminTextField);

        jLabel15.setText(bundle.getString("EtWindow.jLabel15.text")); // NOI18N
        EtoPanel.add(jLabel15);

        etoEaTextField.setText(bundle.getString("EtWindow.etoEaTextField.text")); // NOI18N
        EtoPanel.add(etoEaTextField);

        jLabel16.setText(bundle.getString("EtWindow.jLabel16.text")); // NOI18N
        EtoPanel.add(jLabel16);

        etoAirSpeedTextField.setText(bundle.getString("EtWindow.etoAirSpeedTextField.text")); // NOI18N
        EtoPanel.add(etoAirSpeedTextField);

        jLabel17.setText(bundle.getString("EtWindow.jLabel17.text")); // NOI18N
        EtoPanel.add(jLabel17);

        etoMonthNumberTextField.setText(bundle.getString("EtWindow.etoMonthNumberTextField.text")); // NOI18N
        EtoPanel.add(etoMonthNumberTextField);

        jLabel18.setText(bundle.getString("EtWindow.jLabel18.text")); // NOI18N
        EtoPanel.add(jLabel18);

        etoLatDegreesTextField.setText(bundle.getString("EtWindow.etoLatDegreesTextField.text")); // NOI18N
        EtoPanel.add(etoLatDegreesTextField);

        jLabel19.setText(bundle.getString("EtWindow.jLabel19.text")); // NOI18N
        EtoPanel.add(jLabel19);

        etoLatitudeMinutesTextField.setText(bundle.getString("EtWindow.etoLatitudeMinutesTextField.text")); // NOI18N
        EtoPanel.add(etoLatitudeMinutesTextField);

        jLabel20.setText(bundle.getString("EtWindow.jLabel20.text")); // NOI18N
        EtoPanel.add(jLabel20);

        etoAvMonTempTextField.setText(bundle.getString("EtWindow.etoAvMonTempTextField.text")); // NOI18N
        EtoPanel.add(etoAvMonTempTextField);

        jLabel21.setText(bundle.getString("EtWindow.jLabel21.text")); // NOI18N
        EtoPanel.add(jLabel21);

        etoPrevMonthTempTextField.setText(bundle.getString("EtWindow.etoPrevMonthTempTextField.text")); // NOI18N
        EtoPanel.add(etoPrevMonthTempTextField);

        jLabel22.setText(bundle.getString("EtWindow.jLabel22.text")); // NOI18N
        EtoPanel.add(jLabel22);

        etoAltitudeTextField.setText(bundle.getString("EtWindow.etoAltitudeTextField.text")); // NOI18N
        EtoPanel.add(etoAltitudeTextField);

        jLabel23.setText(bundle.getString("EtWindow.jLabel23.text")); // NOI18N
        EtoPanel.add(jLabel23);

        etoSunHoursTextField.setText(bundle.getString("EtWindow.etoSunHoursTextField.text")); // NOI18N
        EtoPanel.add(etoSunHoursTextField);

        jLabel24.setText(bundle.getString("EtWindow.jLabel24.text")); // NOI18N
        EtoPanel.add(jLabel24);

        etoResultsLabel.setText(bundle.getString("EtWindow.etoResultsLabel.text")); // NOI18N
        EtoPanel.add(etoResultsLabel);

        jLabel26.setText(bundle.getString("EtWindow.jLabel26.text")); // NOI18N
        EtoPanel.add(jLabel26);

        calcEToButton.setText(bundle.getString("EtWindow.calcEToButton.text")); // NOI18N
        calcEToButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcEToButtonActionPerformed(evt);
            }
        });
        EtoPanel.add(calcEToButton);

        jLabel27.setText(bundle.getString("EtWindow.jLabel27.text")); // NOI18N
        EtoPanel.add(jLabel27);

        etoKcTextField.setText(bundle.getString("EtWindow.etoKcTextField.text")); // NOI18N
        EtoPanel.add(etoKcTextField);

        jLabel28.setText(bundle.getString("EtWindow.jLabel28.text")); // NOI18N
        EtoPanel.add(jLabel28);

        etResultsLabel.setText(bundle.getString("EtWindow.etResultsLabel.text")); // NOI18N
        EtoPanel.add(etResultsLabel);

        jLabel30.setText(bundle.getString("EtWindow.jLabel30.text")); // NOI18N
        EtoPanel.add(jLabel30);

        calcETButton.setText(bundle.getString("EtWindow.calcETButton.text")); // NOI18N
        calcETButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcETButtonActionPerformed(evt);
            }
        });
        EtoPanel.add(calcETButton);

        etoTabbedPane.addTab(bundle.getString("EtWindow.EtoPanel.TabConstraints.tabTitle"), EtoPanel); // NOI18N

        getContentPane().add(etoTabbedPane);

        getAccessibleContext().setAccessibleName(bundle.getString("NutrientTypesWindow.AccessibleContext.accessibleName")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eaPoortTminTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eaPoortTminTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eaPoortTminTextFieldActionPerformed

    private void eaPoorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eaPoorButtonActionPerformed
        EaPoor eap = new EaPoor();
        String eapoorTmaxStr = eaPoorTmaxTextField.getText();

        String eapoorTminStr = eaPoortTminTextField.getText();

        String eapoorRhStr = eaPoorRhTextField.getText();

        if (eapoorTmaxStr.length() > 0 && eapoorTminStr.length() > 0 && eapoorRhStr.length() > 0) {
            double eapoorTmaxD = Double.parseDouble(eapoorTmaxStr);
            double eapoorTminD = Double.parseDouble(eapoorTminStr);
            double eapoorRhD = Double.parseDouble(eapoorRhStr);
            eaPoorResultLabel.setText("" + eap.calcEa(eapoorTminD, eapoorTmaxD, eapoorRhD));
            etoTmaxTextField.setText(eapoorTmaxStr);
            etoTminTextField.setText(eapoorTminStr);
            etoEaTextField.setText(eaPoorResultLabel.getText());
            
        }
    }//GEN-LAST:event_eaPoorButtonActionPerformed

    private void etoTminTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etoTminTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etoTminTextFieldActionPerformed

    private void eaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eaButtonActionPerformed
        Ea ea = new Ea();
        String eaTmaxStr = eaTmaxTextField.getText();
        String eaTminStr = eaTminTextField.getText();
        String eaRHMaxStr = eaRHMaxTextField.getText();
        String eaRHMinStr = eaRHMinTextField.getText();
        if (eaTmaxStr.length() > 0 && eaTminStr.length() > 0 && eaRHMaxStr.length() > 0 && eaRHMinStr.length() > 0) {
            double eaTmaxD = Double.parseDouble(eaTmaxStr);
            double eaTminD = Double.parseDouble(eaTminStr);
            double eaRHMaxD = Double.parseDouble(eaRHMaxStr);
            double eaRHMinD = Double.parseDouble(eaRHMinStr);
            eaResultsLabel.setText("" + ea.calcEa(eaTminD, eaTmaxD, eaRHMinD, eaRHMaxD));
            etoTmaxTextField.setText(eaTmaxStr);
            etoTminTextField.setText(eaTminStr);
            etoEaTextField.setText(eaResultsLabel.getText());

        }
    }//GEN-LAST:event_eaButtonActionPerformed

    private void calcEToButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcEToButtonActionPerformed
        String etoTmaxStr = etoTmaxTextField.getText();
        String etoTminStr = etoTminTextField.getText();
        String etoEaStr = etoEaTextField.getText();
        String etoAirSpeedStr = etoAirSpeedTextField.getText();
        String etoMonthNumberStr = etoMonthNumberTextField.getText();
        String etoLatDegreesStr = etoLatDegreesTextField.getText();
        String etoLatitudeMinutes = etoLatitudeMinutesTextField.getText();
        String etoAvMonTempStr = etoAvMonTempTextField.getText();
        String etoPrevMonthTempStr = etoPrevMonthTempTextField.getText();
        String etoAltitudeStr = etoAltitudeTextField.getText();
        String etoSunHoursStr = etoSunHoursTextField.getText();
        if (etoTmaxStr.length() > 0 && etoTminStr.length() > 0 && etoEaStr.length() > 0 && etoAirSpeedStr.length() > 0 && etoMonthNumberStr.length() > 0 && etoLatDegreesStr.length() > 0 && etoLatitudeMinutes.length() > 0 && etoAvMonTempStr.length() > 0 && etoPrevMonthTempStr.length() > 0 && etoAltitudeStr.length() > 0 && etoSunHoursStr.length() > 0) {
            double etoTmaxD = Double.parseDouble(etoTmaxStr);
            double etoTminD = Double.parseDouble(etoTminStr);
            double etoEaD = Double.parseDouble(etoEaStr);
            double etoAirSpeedD = Double.parseDouble(etoAirSpeedStr);
            int etoMonthNumberI = Integer.parseInt(etoMonthNumberStr);
            int etoLatDegreesI = Integer.parseInt(etoLatDegreesStr);
            int etoLatitudeI = Integer.parseInt(etoLatitudeMinutes);
            double etoAvMonTempD = Double.parseDouble(etoAvMonTempStr);
            double etoPrevMonthTempD = Double.parseDouble(etoPrevMonthTempStr);
            double etoAltitudeD = Double.parseDouble(etoAltitudeStr);
            double etoSunHoursD = Double.parseDouble(etoSunHoursStr);
            PenmanMonteith pm = new PenmanMonteith(etoTmaxD, etoTminD, etoEaD, etoAirSpeedD, 15, etoMonthNumberI, etoLatDegreesI, etoLatitudeI, etoAvMonTempD, etoPrevMonthTempD, etoAltitudeD, etoSunHoursD);
            etoResultsLabel.setText("" + pm.calculate());
        }
    }//GEN-LAST:event_calcEToButtonActionPerformed

    private void calcETButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcETButtonActionPerformed
        String etoKcStr = etoKcTextField.getText();
        String etoResultsStr=etoResultsLabel.getText();
        if(etoKcStr.length()>0&&etoResultsStr.length()>0)
        {
            double kc=Double.parseDouble(etoKcStr);
            double eto=Double.parseDouble(etoResultsStr);
            etResultsLabel.setText(""+kc*eto);
        }
    }//GEN-LAST:event_calcETButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new EtWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EaPanel;
    private javax.swing.JPanel EaPoorPanel;
    private javax.swing.JPanel EtoPanel;
    private javax.swing.JButton calcETButton;
    private javax.swing.JButton calcEToButton;
    private javax.swing.JButton eaButton;
    private javax.swing.JButton eaPoorButton;
    private javax.swing.JLabel eaPoorResultLabel;
    private javax.swing.JTextField eaPoorRhTextField;
    private javax.swing.JTextField eaPoorTmaxTextField;
    private javax.swing.JTextField eaPoortTminTextField;
    private javax.swing.JTextField eaRHMaxTextField;
    private javax.swing.JTextField eaRHMinTextField;
    private javax.swing.JLabel eaResultsLabel;
    private javax.swing.JTextField eaTmaxTextField;
    private javax.swing.JTextField eaTminTextField;
    private javax.swing.JLabel etResultsLabel;
    private javax.swing.JTextField etoAirSpeedTextField;
    private javax.swing.JTextField etoAltitudeTextField;
    private javax.swing.JTextField etoAvMonTempTextField;
    private javax.swing.JTextField etoEaTextField;
    private javax.swing.JTextField etoKcTextField;
    private javax.swing.JTextField etoLatDegreesTextField;
    private javax.swing.JTextField etoLatitudeMinutesTextField;
    private javax.swing.JTextField etoMonthNumberTextField;
    private javax.swing.JTextField etoPrevMonthTempTextField;
    private javax.swing.JLabel etoResultsLabel;
    private javax.swing.JTextField etoSunHoursTextField;
    private javax.swing.JTabbedPane etoTabbedPane;
    private javax.swing.JTextField etoTmaxTextField;
    private javax.swing.JTextField etoTminTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables

    /**
     * make the window appear in the appropriate thread
     * to be called from inside the main application frame
     *
     */
    public void displayWindow() {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new EtWindow().setVisible(true);
            }
        });
    }
}
